# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.7
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Supervisor(object):
    def setupUi(self, Supervisor):
        Supervisor.setObjectName("Supervisor")
        Supervisor.resize(1232, 723)
        self.centralwidget = QtWidgets.QWidget(Supervisor)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.listLogClients = QtWidgets.QListWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listLogClients.sizePolicy().hasHeightForWidth())
        self.listLogClients.setSizePolicy(sizePolicy)
        self.listLogClients.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.listLogClients.setSelectionMode(QtWidgets.QAbstractItemView.NoSelection)
        self.listLogClients.setObjectName("listLogClients")
        self.horizontalLayout.addWidget(self.listLogClients)
        self.tableLog = QtWidgets.QTableView(self.groupBox)
        self.tableLog.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableLog.setSelectionMode(QtWidgets.QAbstractItemView.SingleSelection)
        self.tableLog.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableLog.setGridStyle(QtCore.Qt.NoPen)
        self.tableLog.setSortingEnabled(False)
        self.tableLog.setObjectName("tableLog")
        self.tableLog.horizontalHeader().setVisible(True)
        self.tableLog.horizontalHeader().setStretchLastSection(True)
        self.tableLog.verticalHeader().setVisible(False)
        self.tableLog.verticalHeader().setDefaultSectionSize(20)
        self.tableLog.verticalHeader().setMinimumSectionSize(20)
        self.horizontalLayout.addWidget(self.tableLog)
        self.horizontalLayout.setStretch(0, 1)
        self.verticalLayout_4.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.splitter = QtWidgets.QSplitter(self.groupBox_2)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.textCommandLog = QtWidgets.QTextBrowser(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("Monospace")
        self.textCommandLog.setFont(font)
        self.textCommandLog.setObjectName("textCommandLog")
        self.verticalLayout.addWidget(self.textCommandLog)
        self.textCommandInput = CommandInput(self.layoutWidget)
        self.textCommandInput.setObjectName("textCommandInput")
        self.verticalLayout.addWidget(self.textCommandInput)
        self.textCommandHelp = QtWidgets.QTextBrowser(self.splitter)
        self.textCommandHelp.setObjectName("textCommandHelp")
        self.verticalLayout_2.addWidget(self.splitter)
        self.verticalLayout_4.addWidget(self.groupBox_2)
        self.horizontalLayout_2.addLayout(self.verticalLayout_4)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.tableVariables = QtWidgets.QTableWidget(self.groupBox_3)
        self.tableVariables.setObjectName("tableVariables")
        self.tableVariables.setColumnCount(0)
        self.tableVariables.setRowCount(0)
        self.tableVariables.horizontalHeader().setStretchLastSection(True)
        self.tableVariables.verticalHeader().setVisible(False)
        self.verticalLayout_3.addWidget(self.tableVariables)
        self.horizontalLayout_2.addWidget(self.groupBox_3)
        self.horizontalLayout_2.setStretch(0, 3)
        self.horizontalLayout_2.setStretch(1, 1)
        Supervisor.setCentralWidget(self.centralwidget)

        self.retranslateUi(Supervisor)
        QtCore.QMetaObject.connectSlotsByName(Supervisor)

    def retranslateUi(self, Supervisor):
        _translate = QtCore.QCoreApplication.translate
        Supervisor.setWindowTitle(_translate("Supervisor", "pytel pytel-supervisor"))
        self.groupBox.setTitle(_translate("Supervisor", "Logs"))
        self.groupBox_2.setTitle(_translate("Supervisor", "Commands"))
        self.groupBox_3.setTitle(_translate("Supervisor", "Variables"))

from .commandinput import CommandInput
