#
# Configuration file for the Sphinx documentation builder.
#
# This file does only contain a selection of the most common options. For a
# full list see the documentation:
# http://www.sphinx-doc.org/en/stable/config

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
import os
import sys

sys.path.insert(0, os.path.abspath("../../"))

from pyobs.version import __version__ as _pyobs_version  # noqa: E402

# -- Project information -----------------------------------------------------

project = "pyobs"
copyright = "2021, Tim-Oliver Husser"
author = "Tim-Oliver Husser"

# The short X.Y version
version = _pyobs_version
# The full version, including alpha/beta/rc tags
release = _pyobs_version


# -- General configuration ---------------------------------------------------

add_module_names = False

# If your documentation needs a minimal Sphinx version, state it here.
#
# needs_sphinx = '1.0'

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.autodoc",
    "sphinx.ext.githubpages",
    "sphinx.ext.napoleon",
    "sphinx.ext.viewcode",
    "sphinx.ext.autosectionlabel",
    "sphinx.ext.intersphinx",
    # "sphinx_autodoc_typehints",
]

# Scope autosectionlabel-generated labels to their document -- otherwise every docstring's
# repeated "Behavior"/"Input/Output"/"Configuration (YAML)" section headings (and, in
# config_examples/iag50cm.rst specifically, per-host module subsections one level deeper than
# config_examples/iagvt.rst's) collide across pages. Existing :ref:`...` call sites onto
# labels this affects are written as :ref:`document/path:label title` accordingly.
autosectionlabel_prefix_document = True

# intersphinx
intersphinx_mapping = {
    "python": ("https://docs.python.org/3", None),
    "pyobs_alpaca": ("https://docs.pyobs.org/projects/pyobs-alpaca/en/latest/", None),
    "pyobs_weather": ("https://docs.pyobs.org/projects/pyobs-weather/en/latest/", None),
    "pyobs_sbig": ("https://docs.pyobs.org/projects/pyobs-sbig/en/latest/", None),
    "pyobs_asi": ("https://docs.pyobs.org/projects/pyobs-asi/en/latest/", None),
    "pyobs_aravis": ("https://docs.pyobs.org/projects/pyobs-aravis/en/latest/", None),
    "pyobs_fli": ("https://docs.pyobs.org/projects/pyobs-fli/en/latest/", None),
    "pyobs_flipro": ("https://docs.pyobs.org/projects/pyobs-flipro/en/latest/", None),
    "pyobs_qhyccd": ("https://docs.pyobs.org/projects/pyobs-qhyccd/en/latest/", None),
    "pyobs_v4l": ("https://docs.pyobs.org/projects/pyobs-v4l/en/latest/", None),
    "pyobs_zaber": ("https://docs.pyobs.org/projects/pyobs-zaber/en/latest/", None),
    "pyobs_zwoeaf": ("https://docs.pyobs.org/projects/pyobs-zwoeaf/en/latest/", None),
    "pyobs_brot": ("https://docs.pyobs.org/projects/pyobs-brot/en/latest/", None),
}

# napoleon settings
napoleon_google_docstring = True
napoleon_use_param = False
napoleon_use_ivar = True

# typehints
# set_type_checking_flag = True
# autodoc_typehints = "description"

# show c'tor parameters in class only
autoclass_content = "both"

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
# You can specify multiple suffix as a list of string:
#
source_suffix = ".rst"

# The master toctree document.
master_doc = "index"

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path .
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# Be a little nitpicky
nitpicky = True
nitpick_ignore_regex = [
    (r"py:.*", r"numpy.*"),
    (r"py:.*", r"np\..*"),
    (r"py:.*", r"npt\..*"),
    (r"py:.*", r"datetime.*"),
    (r"py:.*", r"aiohttp.*"),
    (r"py:.*", r"astropy.*"),
    (r"py:.*", r"astroplan.*"),
    (r"py:.*", r"fits\..*"),  # astropy.io.fits, conventionally imported as `fits`
    # asyncio primitives report __module__ as their private implementation submodule
    # (asyncio.locks, asyncio.tasks, the C-accelerated _asyncio), not the public asyncio.* alias
    # that's actually indexed in CPython's own docs inventory
    (r"py:.*", r"asyncio\.locks\..*"),
    (r"py:.*", r"asyncio\.tasks\..*"),
    (r"py:.*", r"_asyncio\..*"),
    (r"py:.*", r"pandas.*"),
    (r"py:.*", r"pd\..*"),
    (r"py:.*", r"scipy.*"),
    (r"py:.*", r"sep\..*"),
    (r"py:.*", r"photutils.*"),
    (r"py:.*", r"pydantic.*"),
    (r"py:.*", r"annotated_types.*"),
    (r"py:.*", r"collections.*"),
    (r"py:.*", r"enum.*"),
    (r"py:.*", r"inspect.*"),
    # astropy/astroplan types under their public aliases rather than fully-qualified paths
    (r"py:class", r"SkyCoord"),
    (r"py:class", r"EarthLocation"),
    (r"py:class", r"Observer"),
    # napoleon/autodoc can't cross-reference a full typing.Annotated[...] expression as one object
    (r"py:obj", r"typing\.Annotated\[.*"),
    (r"py:class", r".*Annotated\[.*"),
    (r"py:class", r".*Unit\.[A-Z_]+.*"),
    (r"py:class", r".*'seconds'.*"),
    # pydantic Field(ge=..., le=...) bounds on constrained numeric fields leak into the rendered
    # signature as bare numeric literals, which autodoc then tries to treat as type names
    (r"py:class", r"[0-9]+\.[0-9]+"),
    (r"py:class", r"'?dict\[str.*"),
    (r"py:class", r"Background"),
]
nitpick_ignore = [
    ("py:exc", "IndexError"),
    ("py:exc", "FileNotFoundException"),
    ("py:class", "ObjectClass"),
    ("py:class", "pyobs.object.ObjectClass"),
    ("py:class", "pyobs.object.ProxyType"),
    ("py:class", "pyobs.comm.comm.ProxyType"),
    # module-local exception classes, not part of the public interfaces/exceptions API surface
    ("py:exc", "AltitudeLimitError"),
    ("py:exc", "BodyResolutionError"),
    ("py:exc", "FocusTimeoutError"),
    ("py:exc", "InvalidOrbitalElementsError"),
    ("py:exc", "MissingObserverError"),
    ("py:exc", "MissingSensorError"),
    ("py:exc", "Timeout"),
    ("py:exc", "WeatherDataError"),
    ("py:exc", "WeatherResponseError"),
    # TypeVars / type aliases -- not classes, autodoc can't build a page to link to
    ("py:class", "pyobs.comm.proxy.ProxyType"),
    ("py:class", "pyobs.object.PydanticModel"),
    ("py:class", "pyobs.images.image.MetaClass"),
    ("py:class", "ConfigValue"),
    # private implementation details not part of the public API surface
    ("py:class", "pyobs.comm.proxy._ProxyContext"),
    ("py:class", "pyobs.comm.xmpp.xmppclient.XmppClient"),
    ("py:class", "pyobs.modules.telescope._DummyTelescopeBase"),
    ("py:class", "pyobs.robotic.storage.lco._portal.LcoRequest"),
    # external driver-package classes, documented on that package's own Sphinx site
    ("py:class", "pyobs_aravis.araviscamera.AravisCamera"),
    ("py:class", "pyobs_asi.AsiCoolCamera"),
    # Generic TypeVar bounds rendered by :show-inheritance:, not classes of their own
    ("py:class", "pyobs.modules.pointing.guidingstatistics.guidingstatistics.IN"),
    ("py:class", "pyobs.modules.pointing.guidingstatistics.guidingstatistics.OUT"),
    # malformed self-reference in autodoc's generated bases-list for this class; root cause
    # not identified, low value to chase further (single occurrence)
    ("py:class", "pyobs.interfaces.IPointingHeliographicStonyhurst.IPointingHeliographicStonyhurst"),
    ("py:class", "pyobs.modules.module.F"),
]

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = "sphinx_rtd_theme"
html_theme_options = {
    "collapse_navigation": False,
    "sticky_navigation": True,
    "navigation_depth": 4,
    "display_version": False,
    "logo_only": False,
    "prev_next_buttons_location": "bottom",
    "titles_only": False,
    "style_nav_header_background": "#cccccc",
}
html_logo = "_static/pyobs.gif"
