# Configuration file for the Sphinx documentation builder.
#
# This is the driver-module-conf.py template with the Python-only autodoc/napoleon/viewcode
# extensions removed — for non-Python GUI clients (C++/Qt, TypeScript) that don't have Python
# source for Sphinx to introspect. A Doxygen-backed repo feeds its "Available classes" page via
# doxysphinx instead (see docs-structure-by-project-group.md); a hand-written-only repo just
# omits that page. Everything else (theme, logo, general config) is identical to the Python
# templates, so the rendered site looks the same as the rest of the fleet.
#
# For a full list of options see: http://www.sphinx-doc.org/en/stable/config

# -- Project information -----------------------------------------------------

project = "pyobs-CHANGEME"
copyright = "YYYY, Tim-Oliver Husser"
author = "Tim-Oliver Husser"

# The short X.Y version
# version = "0.16"
# The full version, including alpha/beta/rc tags
# release = "0.16.0"


# -- General configuration ---------------------------------------------------

add_module_names = False

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    "sphinx.ext.githubpages",
    "sphinx.ext.autosectionlabel",
    "sphinx.ext.intersphinx",
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ["_templates"]

# The suffix(es) of source filenames.
source_suffix = ".rst"

# The master toctree document.
master_doc = "index"

# The language for content autogenerated by Sphinx.
language = "en"

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path .
exclude_patterns = []

# The name of the Pygments (syntax highlighting) style to use.
pygments_style = "sphinx"

# Be a little nitpicky
nitpicky = True
nitpick_ignore = []

# intersphinx
intersphinx_mapping = {
    "pyobs": ("https://pyobs-core.readthedocs.io/en/latest/", None),
}

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
html_theme = "sphinx_rtd_theme"
html_theme_options = {
    # No "display_version" here (unlike driver-module-conf.py): sphinx_rtd_theme 3.1.0 removed
    # support for it, and -W (warnings-as-errors) turns the resulting warning into a build
    # failure. Confirmed locally; driver-module-conf.py wasn't changed to match since that's a
    # pre-existing fleet-wide file outside this group's scope.
    "collapse_navigation": False,
    "sticky_navigation": True,
    "navigation_depth": 4,
    "logo_only": False,
    "prev_next_buttons_location": "bottom",
    "titles_only": False,
    "style_nav_header_background": "#cccccc",
}
html_logo = "_static/pyobs.gif"
