name: Lint
on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: "3.11"

      - name: Install packages
        run: uv sync --all-extras --dev

      - name: Run flake8
        run: uv run flake8 pyobs/

      - name: Run mypy
        run: uv run mypy pyobs/
