name: ruff
on: push

jobs:
  ruff:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true
          python-version: "3.13"

      - name: Install packages
        run: uv sync --all-extras --dev

      - name: Run ruff
        run: uv run ruff check pyobs/
